
extra_javascript: [readthedocs-data.js]
pages:
- TOAST Cloud:
  - {Overview: TOAST Cloud/ko/Overview.md}
  - {Getting Started: TOAST Cloud/ko/Getting Started.md}
  - {Release Notes: TOAST Cloud/ko/Release Notes.md}
- Infrastructure:
  - 'Compute & Network ':
    - {Overview: Infrastructure/Compute/ko/Overview.md}
    - {Getting Started: Infrastructure/Compute/ko/Getting Started.md}
    - {Instances User Guide: Infrastructure/Compute/ko/Instances User Guide.md}
    - {Images User Guide: Infrastructure/Compute/ko/Images User Guide.md}
    - {Block Storage User Guide: Infrastructure/Compute/ko/Blockstorage User Guide.md}
    - {NAS (Offline) User Guide: Infrastructure/Compute/ko/NAS User Guide.md}
    - {Security Groups User Guide: Infrastructure/Compute/ko/Security Groups User
        Guide.md}
    - {Networks User Guide: Infrastructure/Compute/ko/Networks User Guide.md}
    - {Load Balancers User Guide: Infrastructure/Compute/ko/Load Balancers User Guide.md}
    - {Windows SSH Guide: Infrastructure/Compute/ko/Windows SSH Guide.md}
    - {Windows SFTP Guide: Infrastructure/Compute/ko/Windows SFTP Guide.md}
    - {Windows Sysprep Guide: Infrastructure/Compute/ko/Windows Sysprep Guide.md}
    - {CIDR Guide: Infrastructure/Compute/ko/CIDR Guide.md}
    - {Monitoring Guide: Infrastructure/Monitoring/ko/Getting Started.md}
    - {Developer`s Guide: Infrastructure/Compute/ko/Developer`s Guide.md}
    - {Release Notes: Infrastructure/Compute/ko/Release Notes.md}
  - Object Storage:
    - {Overview: Infrastructure/Object Storage/ko/Overview.md}
    - {Getting Started: Infrastructure/Object Storage/ko/Getting Started.md}
    - {Developer`s Guide: Infrastructure/Object Storage/ko/Developer`s Guide.md}
    - {Release Notes: Infrastructure/Object Storage/ko/Release Notes.md}
- Contents:
  - Image:
    - {Overview: Contents/Image/ko/Overview.md}
    - {Getting Started: Contents/Image/ko/Getting Started.md}
    - {Developer`s Guide: Contents/Image/ko/Developer`s Guide.md}
    - {Release Notes: Contents/Image/ko/Release Notes.md}
  - CDN:
    - {Overview: Contents/CDN/ko/Overview.md}
    - {Getting Started: Contents/CDN/ko/Getting Started.md}
    - {Developer`s Guide: Contents/CDN/ko/Developer`s Guide.md}
    - {Release Notes: Contents/CDN/ko/Release Notes.md}
- Analytics:
  - App Analytics:
    - Operator`s Guide:
      - {Getting Started: Analytics/App Analytics/Getting Started.md}
      - {Marketing Guide: Analytics/App Analytics/Marketing Guide.md}
    - Developer`s Guide:
      - {Android Developer`s Guide: Analytics/App Analytics/Android Developer`s Guide.md}
      - {iOS Developer`s Guide: Analytics/App Analytics/iOS Developer`s Guide.md}
      - {Unity Developer`s Guide: Analytics/App Analytics/Unity Developer`s Guide.md}
      - {Error Code: Analytics/App Analytics/Error Code.md}
      - {Release Notes: Analytics/App Analytics/Release Notes.md}
  - Log & Crash Search:
    - {Overview: Analytics/Log & Crash Search/ko/Overview.md}
    - {Getting Started: Analytics/Log & Crash Search/ko/Getting Started.md}
    - {Android Developer`s Guide: Analytics/Log & Crash Search/ko/Android Developer`s
        Guide.md}
    - {AndroidNDK Developer`s Guide: Analytics/Log & Crash Search/ko/AndroidNDK Developer`s
        Guide.md}
    - {iOS Developer`s Guide: Analytics/Log & Crash Search/ko/IOS Developer`s Guide.md}
    - Unity Developer`s Guide:
      - {iOS Developer`s Guide: Analytics/Log & Crash Search/ko/iOS Unity Developer`s
          Guide.md}
      - {Android Developer`s Guide: Analytics/Log & Crash Search/ko/Android Unity
          Developer`s Guide.md}
      - {WebGL Developer`s Guide: Analytics/Log & Crash Search/ko/WebGL Developer`s
          Guide.md}
      - {Standalone Developer`s Guide: Analytics/Log & Crash Search/ko/Standalone
          Developer`s Guide.md}
    - {Windows Developer`s Guide: Analytics/Log & Crash Search/ko/Windows Developer`s
        Guide.md}
    - {C# Developer`s Guide: Analytics/Log & Crash Search/ko/C-Sharp Developer`s Guide.md}
    - {Linux Developer`s Guide: Analytics/Log & Crash Search/ko/Linux Developer`s
        Guide.md}
    - {Logback Developer`s Guide: Analytics/Log & Crash Search/ko/Logback Developer`s
        Guide.md}
    - {Log4j Developer`s Guide: Analytics/Log & Crash Search/ko/Log4j Developer`s
        Guide.md}
    - {Log4j.v2 Developer`s Guide: Analytics/Log & Crash Search/ko/Log4j.v2 Developer`s
        Guide.md}
    - {Logstash Developer`s Guide: Analytics/Log & Crash Search/ko/Logstash Developer`s
        Guide.md}
    - {REST API Developer`s Guide: Analytics/Log & Crash Search/ko/REST API Developer`s
        Guide.md}
    - {Release Notes: Analytics/Log & Crash Search/ko/Release Notes.md}
- Game:
  - Leaderboard:
    - {Overview: Game/Leaderboard/ko/Overview.md}
    - {Getting Started: Game/Leaderboard/ko/Getting Started.md}
    - {Developer`s Guide: Game/Leaderboard/ko/Developer`s Guide.md}
    - {Release Notes: Game/Leaderboard/ko/Release Notes.md}
  - Real Time Multiplayer:
    - {Overview: Game/Real Time Multiplayer/ko/Overview.md}
    - {Getting Started: Game/Real Time Multiplayer/ko/Getting Started.md}
    - {Developer`s Guide: Game/Real Time Multiplayer/ko/Developer`s Guide.md}
    - {Release Notes: Game/Real Time Multiplayer/ko/Release Notes.md}
- Notification:
  - Push:
    - {Overview: Notification/Push/ko/Overview.md}
    - {Getting Started: Notification/Push/ko/Getting Started.md}
    - Developer`s Guide:
      - {API v2.0: Notification/Push/ko/Developer`s Guide.md}
      - {API v1.3: Notification/Push/ko/Developer`s Guide v1.3.md}
    - Client SDK Developer`s Guide:
      - {SDK v1.4: Notification/Push/ko/Client SDK Guide.md}
      - {SDK v1.32: Notification/Push/ko/Client SDK Guide v1.32.md}
    - {Release Notes: Notification/Push/ko/Release Notes.md}
  - SMS:
    - {Overview: Notification/SMS/ko/Overview.md}
    - {Getting Started: Notification/SMS/ko/Getting Started.md}
    - Developer`s Guide:
      - {API v2.0: Notification/SMS/ko/Developer`s Guide.md}
      - {API v1.0: Notification/SMS/ko/Developer`s Guide_v1.md}
    - {Release Notes: Notification/SMS/ko/Release Notes.md}
  - Email:
    - {Overview: Notification/E-mail/ko/Overview.md}
    - {Getting Started: Notification/E-mail/ko/Getting Started.md}
    - {Developer`s Guide: Notification/E-mail/ko/Developer`s Guide.md}
    - {Release Notes: Notification/E-mail/ko/Release Notes.md}
  - Alimtalk:
    - {Overview: Notification/Alimtalk/ko/Overview.md}
    - {Getting Started: Notification/Alimtalk/ko/Getting Started.md}
    - {Developer`s Guide: Notification/Alimtalk/ko/Developer`s Guide.md}
    - {Release Notes: Notification/Alimtalk/ko/Release Notes.md}
- Security:
  - AppGuard:
    - {Overview: Security/AppGuard/ko/Overview.md}
    - {Getting Started: Security/AppGuard/ko/Getting Started.md}
    - {Release Notes: Security/AppGuard/ko/Release Notes.md}
  - Security Check:
    - {Overview: Security/Security Check/ko/Overview.md}
    - {Getting Started: Security/Security Check/ko/Getting Started.md}
    - {Release Notes: Security/Security Check/ko/Release Notes.md}
  - Security Monitoring:
    - {Overview: Security/Security Monitoring/ko/Overview.md}
    - {Getting Started: Security/Security Monitoring/ko/Getting Started.md}
    - {Release Notes: Security/Security Monitoring/ko/Release Notes.md}
  - CAPTCHA:
    - {Overview: Security/CAPTCHA/ko/Overview.md}
    - {Developer`s Guide: Security/CAPTCHA/ko/Developer`s Guide.md}
  - OTP:
    - {Overview: Security/OTP/ko/Overview.md}
    - {Developer`s Guide: Security/OTP/ko/Developer`s Guide.md}
- Common:
  - Launching:
    - {Overview: Common/Launching/ko/Overview.md}
    - {Getting Started: Common/Launching/ko/Getting Started.md}
    - {Developer`s Guide: Common/Launching/ko/Developer`s Guide.md}
  - IAP:
    - {Overview: Common/IAP/ko/Overview.md}
    - {Getting Started: Common/IAP/ko/Web Console.md}
    - {Android Developer`s Guide: Common/IAP/ko/Android Developer`s Guide.md}
    - {iOS Developer`s Guide: Common/IAP/ko/iOS Developer`s Guide.md}
    - {Unity Plugin Developer`s Guide: Common/IAP/ko/Unity Plugin Developer`s Guide.md}
    - {Server Developer`s Guide: Common/IAP/ko/Server Developer`s Guide.md}
    - {Store interlocking information: Common/IAP/ko/Store interlocking information.md}
    - {Error Code Guide: Common/IAP/ko/Error Code.md}
    - {Release Notes: Common/IAP/ko/Release Notes.md}
  - Mobile Test:
    - {Overview: Common/Mobile Test/ko/Overview.md}
    - {Getting Started: Common/Mobile Test/ko/Getting Started.md}
    - {Device List: Common/Mobile Test/ko/Device List.md}
    - {Release Notes: Common/Mobile Test/ko/Release Notes.md}
  - Address Search:
    - {Overview: Common/Address Search/ko/Overview.md}
    - {Developer`s Guide: Common/Address Search/ko/Developer`s Guide.md}
  - Maps:
    - {Overview: Common/Maps/ko/Overview.md}
    - {Getting Started: Common/Maps/ko/Getting Started.md}
    - {Developer`s Guide: Common/Maps/ko/Developer`s Guide.md}
    - {Android Developer`s Guide: Common/Maps/ko/Android Developer`s Guide.md}
    - {iOS Developer`s Guide: Common/Maps/ko/iOS Developer`s Guide.md}
    - {Release Notes: Common/Maps/ko/Release Notes.md}
- Management:
  - Managed:
    - {Overview: Management/Managed/ko/Overview.md}
    - {Getting Started: Management/Managed/ko/Getting Started.md}
    - {Release Notes: Management/Managed/ko/Release Notes.md}
- Upcoming Products:
  - CS & BBS:
    - {Overview: Upcoming Products/CS and BBS/ko/Overview.md}
    - {Getting Started: Upcoming Products/CS and BBS/ko/Getting Started.md}
    - {Developer`s Guide: Upcoming Products/CS and BBS/ko/Developer`s Guide.md}
    - {Release Notes: Upcoming Products/CS and BBS/ko/Release Notes.md}
  - Mal-URL Detector:
    - {Overview: Upcoming Products/Mal-URL Detector/ko/Overview.md}
    - {Getting Started: Upcoming Products/Mal-URL Detector/ko/Getting Started.md}
  - WatchDog:
    - {Overview: Upcoming Products/WatchDog/ko/Overview.md}
  - Corporations Search:
    - {Overview: Upcoming Products/Corporations Search/ko/Overview.md}
    - {Developer`s Guide: Upcoming Products/Corporations Search/ko/Developer`s Guide.md}
  - Spell Checker:
    - {Overview: Upcoming Products/Spell Checker/ko/Overview.md}
    - {Getting Started: Upcoming Products/Spell Checker/ko/Getting Started.md}
    - {Developer`s Guide: Upcoming Products/Spell Checker/ko/Developer`s Guide.md}
  - ROLE:
    - {Overview: Upcoming Products/ROLE/ko/Overview.md}
    - {Getting Started: Upcoming Products/ROLE/ko/Getting Started.md}
    - {REST API Developer`s Guide: Upcoming Products/ROLE/ko/RESTFUL API Guide.md}
    - {Client SDK Developer`s Guide: Upcoming Products/ROLE/ko/Client SDK Guide.md}
    - {Spring Client SDK Developer`s Guide: Upcoming Products/ROLE/ko/Spring Client
        SDK Guide.md}
    - {Release Notes: Upcoming Products/ROLE/ko/Release Notes.md}
  - API Gateway:
    - {Overview: Upcoming Products/API Gateway/ko/Overview.md}
    - {Getting Started: Upcoming Products/API Gateway/ko/Getting Started.md}
    - {Developer`s Guide: Upcoming Products/API Gateway/ko/Developer`s Guide.md}
    - {Release Notes: Upcoming Products/API Gateway/ko/Release Notes.md}
  - DNSPlus:
    - {Overview: Upcoming Products/DNSPlus/ko/Overview.md}
    - {Getting Started: Upcoming Products/DNSPlus/ko/Getting Started.md}
    - {Release Notes: Upcoming Products/DNSPlus/ko/Release Notes.md}
  - Mobile Device Info:
    - {Overview: Upcoming Products/Mobile Device Info/ko/Overview.md}
    - {Getting Started: Upcoming Products/Mobile Device Info/ko/Getting Started.md}
    - {Developer`s Guide: Upcoming Products/Mobile Device Info/ko/Developer`s Guide.md}
    - {Release Notes: Upcoming Products/Mobile Device Info/ko/Release Notes.md}
  - Smart Downloader:
    - {Overview: Upcoming Products/Smart Downloader/ko/Overview.md}
    - {Getting Started: Upcoming Products/Smart Downloader/ko/Getting Started.md}
    - {Developer`s Guide: Upcoming Products/Smart Downloader/ko/Developer`s Guide.md}
    - {Release Notes: Upcoming Products/Smart Downloader/ko/Release Notes.md}
  - RTCS:
    - {Overview: Upcoming Products/RTCS/ko/Overview.md}
    - {Getting Started: Upcoming Products/RTCS/ko/Getting Started.md}
    - {Developer`s Guide: Upcoming Products/RTCS/ko/Developer`s Guide.md}
    - {Release Notes: Upcoming Products/RTCS/ko/Release Notes.md}
- Open Source:
  - ToastUI Editor:
    - {Overview: Open Source/ToastUI Editor/ko/Overview.md}
    - {Getting Started: Open Source/ToastUI Editor/ko/Getting Started.md}
  - ToastUI Chart:
    - {Overview: Open Source/ToastUI Chart/ko/Overview.md}
    - {Getting Started: Open Source/ToastUI Chart/ko/Getting Started.md}
    - {Tutorial: Open Source/ToastUI Chart/ko/Tutorial.md}
  - ToastUI Grid:
    - {Overview: Open Source/ToastUI Grid/ko/Overview.md}
    - {Getting Started: Open Source/ToastUI Grid/ko/Getting Started.md}
    - {Features: Open Source/ToastUI Grid/ko/Features.md}
  - Toast Haste:
    - {Overview: Open Source/Toast Haste/ko/Overview.md}
    - {Getting Started: Open Source/Toast Haste/ko/Getting Started.md}
- Downloads:
  - {Latest version: Download.md}
site_name: Toast Cloud Document
theme_dir: toast
